# Generated by Django 4.2 on 2023-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('result', models.FloatField()),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('SUB', 'Sub'), ('MULTI', 'Multi'), ('DIVIDE', 'Divide')], default='ADD', max_length=6)),
            ],
        ),
    ]
